### ISSUE TITLE
keep user logged in after closing the app

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/flutter_sandbox#32]

**Comment by sebastianovide** [comment]
reopening as it is not working: reproduced on Web

**Comment by sebastianovide** [comment]
connected to #38

**Comment by mysticetii** [comment]
When running locally in localhost the login does persist in chrome.  Checks made -> login in one tab, copy the localhost address and open in another tab the user stays logged in. Refresh the page the user stays logged in.

**Comment by mysticetii** [comment]
Issue is fixed by #15
