### ISSUE TITLE
add mapbox_gl widget

### ISSUE THREAD

**Issue by sebastianovide** [Geovation/flutter_sandbox#5]

**Comment by joykuotw** [comment]
I merge the PR for now but leave a note here as there are still some open issues for `flutter-mapbox-gl`.

For example, the current app will crash on _Android 11_ and have to tweak the `build.grable` to fix the bug.

This will be fixed after they merge this PR.
https://github.com/tobrun/flutter-mapbox-gl/pull/489

Also, the current app will hang on iOS if the location permission key is not in the `Info.plist` even though the location is not used. We will add the location key later then.
https://github.com/tobrun/flutter-mapbox-gl/issues/553

**Comment by sebastianovide** [comment]
causes #21, #22
